contacts = {
    "PLB": [
        "pierre.trecourt@premialab.com",
        "marc.fisher@premialab.com",
        "team-it@premialab.com",
        "mohamed.kheri@premialab.com",
        "james.carrington@premialab.com",
        # "dillon.jagatia@premialab.com",
    ],
    "BarclaysUK": [
        "Dhvani and team",
        [
            "dhvani.gupta@barclays.com",
            "remy.penin@barclays.com",
            "ning.wang1@barclays.com",
            "devendra.gangrade@barclays.com",
            "yifan.shen@barclays.com",
            "kenny.lau@barclays.com",
            "benedict.redmond@barclays.com",
        ],
    ],
    "BarclaysUS": [
        "Eugene and team",
        [
            "eugene.gaysinskiy@barclays.com",
            "nora.obringer@barclays.com",
            "kenny.lau@barclays.com",
            "jonny.rees@barclays.com",
            "casper.quint@barclays.com",
            "han.zheng@barclays.com",
            "srinidhi.cadabarangaraju@barclays.com",
            "saaj.kothari@barclays.com",
            "yilong.zhao@barclays.com",
        ],
    ],
    "BNP": [
        "Pierre-Louis and team",
        [
            "pierre-louis.nack@bnpparibas.com",
            "eric.nicolas@bnpparibas.com",
        ],
    ],
    "BofA": [
        "Team",
        [
            "ben.barr@bofa.com",
            "alexandre.prevost@bofa.com",
            "rhita.mourtada@bofa.com",
            "marc.assouline@bofa.com",
            "marc.perrigault@bofa.com",
            # "glendingwei.tuan@bofa.com",
            # "amicie.durantdesaulnois@bofa.com",
            "kamaru.alofoje@bofa.com",
            # "dan.haloua@bofa.com",
            "dg.investable_indices_3rd_party_platforms@bofa.com",
        ],
    ],
    "CIBC": [
        "Lola and team",
        [
            "Lola.Tsetlin@cibc.com",
            "Alexandra.Krystal@cibc.com",
        ],
    ],
    "Citi": [
        "Amandine and team",
        [
            "amandine.descales@citi.com",
            "marine.renucci@citi.com",
            "ashher.shaikh@citi.com",
            "ayush6.gupta@citi.com",
            "aruna.tatavarty@citi.com",
            "umberto.barbieri@citi.com",
            "neil.mussett@citi.com",
            "yuqi.shen@citi.com",
            "benjamin1.thomas@citi.com",
            "indexservices@citi.com",
        ],
    ],
    "DB": [
        "Sorin and team",
        [
            "Sorin.Ionescu@db.com",
            "Jenny.Dawson@db.com",
            "Sophia.Zhang@db.com",
            "Valery.Sorokin@db.com",
            "Ambarish.Barpujari@db.com",
            "Index.Data@db.com",
        ],
    ],
    "GS": [
        "Romain",
        [
            "Romain.Bayle@gs.com",
            "Francois.Mauran@gs.com",
            "Martin.Luehrmann@gs.com",
        ],
    ],
    "HSBC": [
        "Younes and team",
        [
            "younes.elamrani@hsbc.com",
            # "romain.benvenuto@hsbc.com",
            "david.r.odenath@us.hsbc.com",
            "daniil.valeev@hsbcib.com",
            "karim.lamissa.traore@hsbc.com",
            "priya1.khulbe@hsbc.co.in",
            "jeremy.dunate@hsbc.com",
        ],
    ],
    "JPM": [
        "Dennis and team",
        [
            "dennis.harrison@jpmorgan.com",
            "deepak.k.maharaj@jpmorgan.com",
            "kanika.gupta@jpmchase.com",
            "JPMorgan_Strategic_Indices@jpmorgan.com",
        ],
    ],
    "Macquarie": [
        "Sowmini and team",
        [
            "Sowmini.Chandra@macquarie.com",
            "Maia.Mathieson@macquarie.com",
            "Cormac.Gaffney@macquarie.com",
            "Jules.Baretta@macquarie.com",
            "Natasha.Wirszycz@macquarie.com",
            "CIP@macquarie.com",
        ],
    ],
    "MS": [
        "Mark and team",
        [
            "Mark.Sullivan@morganstanley.com",
            "Anika.Goel@MorganStanley.com",
            "Daniel.Kheng@morganstanley.com",
            "Jean.Boyer@morganstanley.com",
        ],
    ],
    "Natixis": [
        "Frederic and team",
        [
            "valentine.biais@natixis.com",
            "noureddine.oulidazouz@natixis.com",
            "florentin.randazzo@natixis.com",
            "frederic.goasguen@natixis.com",
            "jean-francois.zubillaga@natixis.com",
            "salim.ghali-ext@natixis.com",
            "thibaut.hagel@natixis.com",
            "celia.pratz@natixis.com",
            "indexstructuring-origination@nomura.com",
        ],
    ],
    "Nomura": [
        "Rebecca and team",
        [
            "rebecca.drudi@nomura.com",
            "steve.altemus@nomura.com",
            "rohit.baddi@nomura.com",
            "indexstructuring-origination@nomura.com",
        ],
    ],
    "RBC": [
        "Chris and team",
        [
            "christopher.dubois@rbccm.com",
            "emma.steiner@rbccm.com",
        ],
    ],
    "SG": [
        "Kirt and team",
        [
            "mehdi.zouhair@sgcib.com",
            "kirt.bains@sgcib.com",
            "wiam.rochdi@sgcib.com",
            "EUR-MARK-SPS-ISS-XA@sgcib.com",
            "list.cas-mark-eng-sgi-rpg@socgen.com",
            "marvin.blandin@sgcib.com",
            "foued.jaziri@sgcib.com",
            "anastasia.chernozubova@sgcib.com",
        ],
    ],
    "UBS": [
        "Ami and Chenglong",
        [
            "chenglong.liu@ubs.com",
            "hadassa.brunschwig@ubs.com",
            "hawa.bah-bah@ubs.com",
            "shenru.li@ubs.com",
            "ami.kapre@ubs.com",
            "shreyash.havale@ubs.com",
        ],
    ],
}
