pm_bank_dict = {
    "BarclaysUS": "",
    "BarclaysUK": "",
    "BNP": "",
    "BofA": "",
    "CIBC": "",
    "Citi": "",
    "DB": "",
    "GS": "",
    "HSBC": "",
    "JPM": "",
    "Macquarie": "",
    "MS": "",
    "Natixis": "",
    "Nomura": "",
    "RBC": "",
    "SG": "",
    "UBS": "",
}
